language: java
jdk:
  - oraclejdk8
install: true
env:
  global:
    - CODECOV_TOKEN=:6004f904-74f6-4b88-b9b9-0a5496c50001

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)